---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: redis
  namespace: redis
spec:
  repo: 'https://charts.bitnami.com/bitnami'
  chart: redis
  version: 20.6.0
  targetNamespace: redis
  valuesContent: |-
    global:
      redis:
        password: 'qUwTt8g9it'
    pdb:
      create: true
    replica:
      replicaCount: 1