apiVersion: v1
kind: Secret
metadata:
  name: build-gitlab-runner
  namespace: gitlab
  labels:
    manual: "yes"
type: Opaque
stringData:
  runner-registration-token: ""
  # тут подставляем полученный в WEB интерфейсе токен
  runner-token: "glrt-B3ah2WmHWK-ANmK9yTRe"
  
  # S3 cache parameters
  accesskey: "admin"
  secretkey: "password"