apiVersion: v1
kind: Secret
metadata:
  name: dev-gitlab-runner
  namespace: gitlab
  labels:
    manual: "yes"
type: Opaque
stringData:
  runner-registration-token: ""
  # тут подставляем полученный в WEB интерфейсе токен
  runner-token: "glrt-mqhgydMjxY-CroYMWgQ2"
  
  # S3 cache parameters
  accesskey: "admin"
  secretkey: "password"